name: Docker build and deploy
on:
  push:
    branches:
      - main
jobs:
  build_production:
    runs-on: ubuntu-latest
    env:
      DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE}}
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ DOCKERHUB_USERNAME }}
        password: ${{ DOCKERHUB_TOKEN }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ DOCKER_IMAGE }}
    - name: Deploy code to server
      run: |
        mkdir -p ~/.ssh
        chmod 755 ~/.ssh
        ssh-keyscan -H $DEPLOY_HOST >> ~/.ssh/known_hosts
        echo "$SSH_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh -o StrictHostKeyChecking=no ubuntu@$DEPLOY_HOST "docker pull $DOCKER_IMAGE"
        ssh -o StrictHostKeyChecking=no ubuntu@$DEPLOY_HOST "docker stop longtv_github || true && docker rm longtv_github || true"
        ssh -o StrictHostKeyChecking=no ubuntu@$DEPLOY_HOST "docker run -p 3002:80 -d --name longtv_github $DOCKER_IMAGE"